#!/usr/bin/env python3
"""H028: public/private action-gradient HS-JEPA.

H027 showed that wrapping existing posteriors with another public/private gate
does not safely recover H012-beating transfer. H028 changes the prediction target:
known public submissions are treated as interventions from H012, and the target
representation is the public LB response to those intervention vectors.

The learned object is a low-rank cell-level public action-gradient. Candidate
submissions are generated by moving H012 along that learned gradient, then
stress-tested through the existing H024/H025 public/action-health sensors.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import hashlib
import importlib.util
import shutil
import sys

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
HITL = ROOT / "hitl"
OUT = HITL / "h028_public_private_gradient_jepa"
OUT.mkdir(parents=True, exist_ok=True)

TARGETS = ["Q1", "Q2", "Q3", "S1", "S2", "S3", "S4"]
KEYS = ["subject_id", "sleep_date", "lifelog_date"]
EPS = 1.0e-6
H012 = "submission_h012_public_equation_top_all_k1200_a0.7_uploadsafe.csv"
H012_LB = 0.5681234831


@dataclass(frozen=True)
class GradientFit:
    feature_set: str
    alpha: float
    cols: list[str]
    beta: np.ndarray
    mu: np.ndarray
    sd: np.ndarray
    intercept: float
    loo_mae: float
    loo_rmse: float
    loo_spearman: float
    loo_pair_acc: float
    loo_pred: np.ndarray
    public_perm_p: float


def import_module(path: Path, name: str) -> object:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(str(path))
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def clip_prob(x: np.ndarray) -> np.ndarray:
    return np.clip(np.asarray(x, dtype=np.float64), EPS, 1.0 - EPS)


def logit(x: np.ndarray) -> np.ndarray:
    p = clip_prob(x)
    return np.log(p / (1.0 - p))


def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.asarray(x, dtype=np.float64)))


def robust_z(x: pd.Series | np.ndarray) -> np.ndarray:
    arr = np.asarray(x, dtype=np.float64)
    med = np.nanmedian(arr)
    mad = np.nanmedian(np.abs(arr - med))
    scale = 1.4826 * mad if mad > 1.0e-12 else np.nanstd(arr)
    if not np.isfinite(scale) or scale < 1.0e-12:
        scale = 1.0
    return np.nan_to_num((arr - med) / scale)


def spearman(a: np.ndarray, b: np.ndarray) -> float:
    if len(a) < 3:
        return float("nan")
    ra = pd.Series(a).rank(method="average").to_numpy(dtype=np.float64)
    rb = pd.Series(b).rank(method="average").to_numpy(dtype=np.float64)
    if np.std(ra) < 1.0e-12 or np.std(rb) < 1.0e-12:
        return float("nan")
    return float(np.corrcoef(ra, rb)[0, 1])


def pairwise_accuracy(y: np.ndarray, pred: np.ndarray) -> float:
    ok = 0
    total = 0
    for i in range(len(y)):
        for j in range(i + 1, len(y)):
            dy = y[i] - y[j]
            dp = pred[i] - pred[j]
            if abs(dy) < 1.0e-12:
                continue
            total += 1
            ok += int(np.sign(dy) == np.sign(dp))
    return float(ok / total) if total else float("nan")


def md_table(frame: pd.DataFrame, n: int = 20) -> str:
    if frame.empty:
        return "_empty_"
    view = frame.head(n).copy()
    for col in view.columns:
        if pd.api.types.is_float_dtype(view[col]):
            view[col] = view[col].map(lambda x: "" if pd.isna(x) else f"{float(x):.9f}")
    view = view.fillna("")
    headers = [str(c) for c in view.columns]
    rows = [[str(v).replace("\n", " ") for v in row] for row in view.to_numpy()]
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    out.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(out)


def safe_id(text: str, limit: int = 72) -> str:
    out = []
    for ch in str(text):
        out.append(ch if ch.isalnum() or ch in "._-" else "_")
    return "".join(out).strip("_")[:limit].strip("_")


def short_hash(arr: np.ndarray) -> str:
    return hashlib.sha1(np.round(np.asarray(arr, dtype=np.float64), 12).tobytes()).hexdigest()[:8]


def fit_ridge(train_x: np.ndarray, train_y: np.ndarray, alpha: float) -> tuple[float, np.ndarray, np.ndarray, np.ndarray]:
    mu = np.nanmean(train_x, axis=0)
    sd = np.nanstd(train_x, axis=0)
    sd = np.where(sd < 1.0e-12, 1.0, sd)
    x = np.nan_to_num((train_x - mu) / sd)
    xa = np.column_stack([np.ones(len(x)), x])
    penalty = np.eye(xa.shape[1], dtype=np.float64) * alpha
    penalty[0, 0] = 0.0
    beta_all = np.linalg.pinv(xa.T @ xa + penalty) @ xa.T @ train_y
    return float(beta_all[0]), beta_all[1:], mu, sd


def predict_ridge(x: np.ndarray, intercept: float, beta: np.ndarray, mu: np.ndarray, sd: np.ndarray) -> np.ndarray:
    xz = np.nan_to_num((x - mu) / sd)
    return intercept + xz @ beta


def load_runtime():
    h026 = import_module(HITL / "h026_public_private_calibration_veto_jepa.py", "h026_public_private_calibration_veto_jepa")
    return h026, h026.prepare_runtime()


def target_subset_mask(subset: str, n_rows: int) -> np.ndarray:
    groups = {
        "all": TARGETS,
        "Q": ["Q1", "Q2", "Q3"],
        "S": ["S1", "S2", "S3", "S4"],
        "QS_quality": ["Q1", "Q3", "S1", "S2", "S3", "S4"],
        "Q2S1S3": ["Q2", "S1", "S3"],
        "Q2S3": ["Q2", "S3"],
        "S1S2S3": ["S1", "S2", "S3"],
        "Q2S1": ["Q2", "S1"],
    }
    targets = groups.get(subset, [subset] if subset in TARGETS else [])
    mask = np.zeros((n_rows, len(TARGETS)), dtype=bool)
    for target in targets:
        mask[:, TARGETS.index(target)] = True
    return mask


def merge_named_cells(cells: pd.DataFrame, path: Path, rename: dict[str, str]) -> pd.DataFrame:
    if not path.exists():
        for dst in rename.values():
            cells[dst] = 0.0
        return cells
    df = pd.read_csv(path)
    keep = ["row", "target"] + [c for c in rename if c in df.columns]
    df = df[keep].rename(columns=rename)
    return cells.merge(df, on=["row", "target"], how="left")


def build_cell_state(rt) -> tuple[pd.DataFrame, dict[str, list[str]]]:
    merged_path = HITL / "h027_public_private_aware_generator_jepa" / "h027_merged_cell_state.csv"
    if merged_path.exists():
        cells = pd.read_csv(merged_path)
    else:
        rows = []
        for row in range(rt.h012_prob.shape[0]):
            for t_i, target in enumerate(TARGETS):
                rows.append({"row": row, "target": target, "target_i": t_i, "h012_prob": float(rt.h012_prob[row, t_i])})
        cells = pd.DataFrame(rows)

    cells = merge_named_cells(
        cells,
        HITL / "h012_public_equation_jepa_jackpot" / "h012_cell_posterior.csv",
        {
            "posterior_prob": "h012_posterior_prob",
            "posterior_minus_base": "h012_posterior_minus_base",
            "logit_delta_to_posterior": "h012_logit_delta_to_posterior",
            "direction_consistency": "h012_direction_consistency",
            "cell_score": "h012_cell_score",
        },
    )
    cells = cells.drop_duplicates(["row", "target"], keep="last").sort_values(["row", "target_i"]).reset_index(drop=True)

    sample = rt.sample.copy()
    sample["row"] = np.arange(len(sample), dtype=int)
    sample["sleep_date"] = pd.to_datetime(sample["sleep_date"])
    sample["lifelog_date"] = pd.to_datetime(sample["lifelog_date"])
    sample["sleep_dow"] = sample["sleep_date"].dt.dayofweek.astype(int)
    sample["lifelog_dow"] = sample["lifelog_date"].dt.dayofweek.astype(int)
    sample["date_gap_days"] = (sample["sleep_date"] - sample["lifelog_date"]).dt.days.astype(float)
    sample["row_norm"] = sample["row"] / max(len(sample) - 1, 1)
    sample["row_sin1"] = np.sin(2 * np.pi * sample["row_norm"])
    sample["row_cos1"] = np.cos(2 * np.pi * sample["row_norm"])
    sample["row_sin5"] = np.sin(10 * np.pi * sample["row_norm"])
    sample["row_cos5"] = np.cos(10 * np.pi * sample["row_norm"])
    sample["subject_idx"] = pd.factorize(sample["subject_id"].astype(str), sort=True)[0]
    subject_counts = sample.groupby("subject_id")["row"].transform("size").astype(float)
    sample["within_subject_order"] = sample.groupby("subject_id").cumcount().astype(float)
    sample["within_subject_norm"] = sample["within_subject_order"] / np.maximum(subject_counts - 1.0, 1.0)
    sample["subject_block_size"] = subject_counts

    cells = cells.merge(
        sample[
            [
                "row",
                "subject_id",
                "sleep_dow",
                "lifelog_dow",
                "date_gap_days",
                "row_norm",
                "row_sin1",
                "row_cos1",
                "row_sin5",
                "row_cos5",
                "subject_idx",
                "within_subject_norm",
                "subject_block_size",
            ]
        ],
        on="row",
        how="left",
    )

    for target in TARGETS:
        cells[f"target_{target}"] = cells["target"].eq(target).astype(float)
    for sid in sorted(cells["subject_id"].astype(str).dropna().unique()):
        cells[f"subject_{safe_id(sid, 24)}"] = cells["subject_id"].astype(str).eq(sid).astype(float)
    for dow in range(7):
        cells[f"sleep_dow_{dow}"] = (cells["sleep_dow"] == dow).astype(float)
        cells[f"lifelog_dow_{dow}"] = (cells["lifelog_dow"] == dow).astype(float)

    numeric_cols = []
    for col in cells.columns:
        if col in {"row", "target", "target_i", "subject_id"}:
            continue
        if pd.api.types.is_bool_dtype(cells[col]):
            cells[col] = cells[col].astype(float)
        if pd.api.types.is_numeric_dtype(cells[col]):
            vals = cells[col].to_numpy(dtype=np.float64)
            if np.nanstd(vals) > 1.0e-12:
                cells[col] = np.nan_to_num(vals, nan=0.0, posinf=0.0, neginf=0.0)
                numeric_cols.append(col)

    def by_prefix(prefixes: tuple[str, ...]) -> list[str]:
        return [c for c in numeric_cols if c.startswith(prefixes)]

    route_cols = by_prefix(("h012_", "h015_", "h016_", "h020_", "h021_", "h023_", "h014_"))
    human_cols = by_prefix(("h021_", "h023_", "h014_"))
    public_cols = by_prefix(("h012_", "h015_", "h016_", "h020_"))
    identity_cols = by_prefix(("target_", "subject_", "sleep_dow_", "lifelog_dow_")) + [
        c for c in ["row_norm", "row_sin1", "row_cos1", "row_sin5", "row_cos5", "within_subject_norm", "subject_block_size", "date_gap_days"] if c in numeric_cols
    ]
    feature_sets = {
        "identity": identity_cols,
        "public_routes": sorted(set(identity_cols + public_cols)),
        "human_memory": sorted(set(identity_cols + human_cols)),
        "routes_no_subject": sorted(set(route_cols + [c for c in identity_cols if not c.startswith("subject_")])),
        "all": sorted(set(numeric_cols)),
    }
    feature_sets = {k: [c for c in v if c in numeric_cols] for k, v in feature_sets.items() if len(v) >= 4}
    return cells, feature_sets


def known_public_moves(rt, cells: pd.DataFrame) -> pd.DataFrame:
    known = rt.h024.read_public_observations()
    base = logit(rt.h012_prob).reshape(-1)
    rows = []
    for rec in known.to_dict("records"):
        path = rt.h024.locate(str(rec["file"]))
        if path is None:
            continue
        sub = rt.h024.load_sub(path, rt.sample)
        arr = sub[TARGETS].to_numpy(dtype=np.float64)
        move = logit(arr).reshape(-1) - base
        rows.append(
            {
                "file": str(rec["file"]),
                "resolved_path": str(path),
                "public_lb": float(rec["public_lb"]),
                "delta_vs_h012": float(rec["public_lb"] - H012_LB),
                "mean_abs_logit_move": float(np.mean(np.abs(move))),
                "changed_cells": int(np.sum(np.abs(arr.reshape(-1) - rt.h012_prob.reshape(-1)) > 1.0e-6)),
                "move_logit": move,
            }
        )
    out = pd.DataFrame(rows).sort_values("public_lb").reset_index(drop=True)
    if len(out) < 8:
        raise RuntimeError("not enough public sensors for H028")
    return out


def aggregate_moves(moves: np.ndarray, feature_matrix: np.ndarray) -> np.ndarray:
    return (moves @ feature_matrix) / max(feature_matrix.shape[0], 1)


def evaluate_gradient_models(
    known: pd.DataFrame,
    cells: pd.DataFrame,
    feature_sets: dict[str, list[str]],
    n_perm: int = 250,
) -> tuple[pd.DataFrame, pd.DataFrame, GradientFit]:
    moves = np.vstack(known["move_logit"].to_list()).astype(np.float64)
    y = known["delta_vs_h012"].to_numpy(dtype=np.float64)
    alphas = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
    model_rows = []
    pred_rows = []
    fits: list[GradientFit] = []

    for set_name, cols in feature_sets.items():
        f = cells[cols].to_numpy(dtype=np.float64)
        x = aggregate_moves(moves, f)
        if x.shape[1] > 160:
            variances = np.nanvar(x, axis=0)
            keep = np.argsort(variances)[-160:]
            cols_use = [cols[i] for i in keep]
            x_use = x[:, keep]
            f_use = f[:, keep]
        else:
            cols_use = cols
            x_use = x
            f_use = f
        for alpha in alphas:
            loo = np.zeros(len(known), dtype=np.float64)
            for i in range(len(known)):
                train_mask = np.ones(len(known), dtype=bool)
                train_mask[i] = False
                intercept, beta, mu, sd = fit_ridge(x_use[train_mask], y[train_mask], alpha)
                loo[i] = predict_ridge(x_use[[i]], intercept, beta, mu, sd)[0]
            mae = float(np.mean(np.abs(loo - y)))
            rmse = float(np.sqrt(np.mean((loo - y) ** 2)))
            rho = spearman(y, loo)
            pair_acc = pairwise_accuracy(y, loo)
            intercept, beta, mu, sd = fit_ridge(x_use, y, alpha)
            full_pred = predict_ridge(x_use, intercept, beta, mu, sd)
            fits.append(
                GradientFit(
                    feature_set=set_name,
                    alpha=float(alpha),
                    cols=cols_use,
                    beta=beta,
                    mu=mu,
                    sd=sd,
                    intercept=intercept,
                    loo_mae=mae,
                    loo_rmse=rmse,
                    loo_spearman=rho,
                    loo_pair_acc=pair_acc,
                    loo_pred=loo,
                    public_perm_p=1.0,
                )
            )
            model_rows.append(
                {
                    "feature_set": set_name,
                    "alpha": float(alpha),
                    "n_features": len(cols_use),
                    "loo_mae": mae,
                    "loo_rmse": rmse,
                    "loo_spearman": rho,
                    "loo_pair_acc": pair_acc,
                    "full_fit_mae": float(np.mean(np.abs(full_pred - y))),
                    "h012_delta_pred_loo": float(loo[known["file"].eq(H012).to_numpy()][0]) if known["file"].eq(H012).any() else np.nan,
                }
            )
            for j, rec in known[["file", "public_lb", "delta_vs_h012"]].iterrows():
                pred_rows.append(
                    {
                        "feature_set": set_name,
                        "alpha": float(alpha),
                        "file": rec["file"],
                        "public_lb": float(rec["public_lb"]),
                        "delta_vs_h012": float(rec["delta_vs_h012"]),
                        "loo_pred_delta": float(loo[j]),
                        "loo_error": float(loo[j] - rec["delta_vs_h012"]),
                    }
                )

    model_df = pd.DataFrame(model_rows)
    model_df["rank_score"] = (
        model_df["loo_mae"]
        + 0.65 * model_df["loo_rmse"]
        - 0.00020 * model_df["loo_pair_acc"].fillna(0.0)
        - 0.00010 * model_df["loo_spearman"].fillna(0.0)
    )
    model_df = model_df.sort_values(["rank_score", "loo_mae"]).reset_index(drop=True)
    pred_df = pd.DataFrame(pred_rows)

    best_key = (str(model_df.iloc[0]["feature_set"]), float(model_df.iloc[0]["alpha"]))
    selected = next(fit for fit in fits if fit.feature_set == best_key[0] and abs(fit.alpha - best_key[1]) < 1.0e-12)
    selected_cols = selected.cols
    f = cells[selected_cols].to_numpy(dtype=np.float64)
    x = aggregate_moves(moves, f)
    rng = np.random.default_rng(28028)
    null_mae = []
    real_mae = selected.loo_mae
    for _ in range(n_perm):
        y_perm = rng.permutation(y)
        loo = np.zeros(len(known), dtype=np.float64)
        for i in range(len(known)):
            train_mask = np.ones(len(known), dtype=bool)
            train_mask[i] = False
            intercept, beta, mu, sd = fit_ridge(x[train_mask], y_perm[train_mask], selected.alpha)
            loo[i] = predict_ridge(x[[i]], intercept, beta, mu, sd)[0]
        null_mae.append(float(np.mean(np.abs(loo - y_perm))))
    p = float(np.mean(np.asarray(null_mae) <= real_mae))
    selected = GradientFit(
        feature_set=selected.feature_set,
        alpha=selected.alpha,
        cols=selected.cols,
        beta=selected.beta,
        mu=selected.mu,
        sd=selected.sd,
        intercept=selected.intercept,
        loo_mae=selected.loo_mae,
        loo_rmse=selected.loo_rmse,
        loo_spearman=selected.loo_spearman,
        loo_pair_acc=selected.loo_pair_acc,
        loo_pred=selected.loo_pred,
        public_perm_p=p,
    )
    model_df.loc[
        (model_df["feature_set"].eq(selected.feature_set)) & (model_df["alpha"].eq(selected.alpha)),
        "public_perm_p",
    ] = p
    model_df["public_perm_p"] = model_df["public_perm_p"].fillna(1.0)
    pd.DataFrame({"perm_loo_mae": null_mae, "real_loo_mae": real_mae}).to_csv(OUT / "h028_gradient_permutation_null.csv", index=False)
    return model_df, pred_df, selected


def gradient_vector(cells: pd.DataFrame, fit: GradientFit) -> np.ndarray:
    f = cells[fit.cols].to_numpy(dtype=np.float64)
    coeff = fit.beta / fit.sd
    return (f @ coeff) / max(len(cells), 1)


def candidate_delta_prediction(move_flat: np.ndarray, cells: pd.DataFrame, fit: GradientFit) -> float:
    f = cells[fit.cols].to_numpy(dtype=np.float64)
    x = aggregate_moves(move_flat.reshape(1, -1), f)
    return float(predict_ridge(x, fit.intercept, fit.beta, fit.mu, fit.sd)[0])


def cell_energy(move_logit: np.ndarray, dirs: list[np.ndarray]) -> np.ndarray:
    if not dirs:
        return np.zeros_like(move_logit, dtype=np.float64)
    energy = np.zeros_like(move_logit, dtype=np.float64)
    for direction in dirs:
        scale = float(np.quantile(np.abs(direction), 0.95))
        scale = scale if scale > 1.0e-12 else 1.0
        energy += np.maximum(0.0, move_logit * direction / scale)
    return energy / max(len(dirs), 1)


def generate_variants(rt, h026, cells: pd.DataFrame, fit: GradientFit, known: pd.DataFrame) -> pd.DataFrame:
    base_logit = logit(rt.h012_prob)
    base_flat = base_logit.reshape(-1)
    e247_path = rt.h024.locate("submission_e247_featnn1_nn_smooth_sum_top34_f1ff7e86.csv")
    e247 = rt.h024.load_sub(e247_path, rt.sample)[TARGETS].to_numpy(dtype=np.float64) if e247_path is not None else rt.h012_prob.copy()
    e247_move = (logit(e247) - base_logit).reshape(-1)
    h012_from_e247 = -e247_move
    g = gradient_vector(cells, fit)
    scale = float(np.quantile(np.abs(g), 0.95))
    if scale <= 1.0e-15:
        scale = 1.0
    g_unit = np.tanh(g / scale)
    gain_score = -g * h012_from_e247
    rollback_score = e247_move * g
    dirs = h026.anchor_dirs(rt)
    public_bad = cell_energy(np.sign(-g).reshape(rt.h012_prob.shape), dirs["bad"]).reshape(-1)
    public_good = cell_energy(np.sign(-g).reshape(rt.h012_prob.shape), dirs["good"]).reshape(-1)

    cell_private = cells.get("h014_private_safe_score", pd.Series(np.zeros(len(cells)))).to_numpy(dtype=np.float64)
    cell_hs = np.nan_to_num(
        cells.get("h023_hs_h023_agree", pd.Series(np.zeros(len(cells)))).to_numpy(dtype=np.float64), nan=0.0
    )
    rows = []
    known_names = set(known["file"].astype(str))
    target_subsets = ["all", "Q", "S", "QS_quality", "Q2S1S3", "Q2S3", "S1S2S3", "Q2S1"]
    modes = {
        "descent": [0.015, 0.03, 0.06, 0.12, 0.22, 0.36],
        "rollback": [0.15, 0.30, 0.50, 0.75, 1.00],
        "amplify_h012": [0.08, 0.16, 0.28, 0.45, 0.70],
        "hybrid": [0.10, 0.20, 0.35, 0.55],
    }
    topks = [30, 60, 100, 180, 320, 520, 800, 1200, 1600]
    n_rows = rt.h012_prob.shape[0]

    for subset in target_subsets:
        subset_mask = target_subset_mask(subset, n_rows).reshape(-1)
        if not subset_mask.any():
            continue
        for mode, alphas in modes.items():
            if mode == "descent":
                base_move = -g_unit
                score = np.abs(g) + 0.15 * robust_z(cell_private) + 0.10 * robust_z(cell_hs) - 0.05 * robust_z(public_bad)
                good_mask = (base_move * g) < 0
            elif mode == "rollback":
                base_move = e247_move
                score = -rollback_score + 0.20 * robust_z(cell_private) - 0.05 * robust_z(public_bad)
                good_mask = rollback_score < 0
            elif mode == "amplify_h012":
                base_move = h012_from_e247
                score = -gain_score + 0.10 * robust_z(cell_hs) + 0.05 * robust_z(public_good)
                good_mask = gain_score < 0
            else:
                base_move = 0.55 * (-g_unit) + 0.45 * np.where(rollback_score < 0, e247_move, 0.0)
                score = np.abs(g) - 0.35 * np.maximum(rollback_score, 0.0) + 0.10 * robust_z(cell_private)
                good_mask = (base_move * g) < 0

            candidate_mask = subset_mask & good_mask & np.isfinite(score)
            if not candidate_mask.any():
                continue
            order = np.where(candidate_mask, score, -np.inf)
            ranked = np.argsort(order)[::-1]
            ranked = ranked[np.isfinite(order[ranked])]
            for top_k in topks:
                if top_k > len(ranked):
                    continue
                chosen = ranked[:top_k]
                for alpha in alphas:
                    move = np.zeros_like(base_flat)
                    move[chosen] = alpha * base_move[chosen]
                    if np.max(np.abs(move)) < 1.0e-12:
                        continue
                    out_logit = base_flat + move
                    q = sigmoid(out_logit).reshape(rt.h012_prob.shape)
                    out = rt.h012.copy()
                    out[TARGETS] = np.clip(q, EPS, 1.0 - EPS)
                    file_stem = (
                        f"submission_h028_pubgrad_{mode}_{subset}_k{top_k}_a{str(alpha).replace('.', 'p')}_"
                        f"{safe_id(fit.feature_set)}"
                    )
                    out_path = OUT / f"{file_stem}_{short_hash(q)}.csv"
                    out.to_csv(out_path, index=False)
                    delta_prob = q - rt.h012_prob
                    move_mat = move.reshape(rt.h012_prob.shape)
                    rows.append(
                        {
                            "file": f"hitl/h028_public_private_gradient_jepa/{out_path.name}",
                            "resolved_path": str(out_path),
                            "mode": mode,
                            "target_subset": subset,
                            "top_k": int(top_k),
                            "alpha": float(alpha),
                            "fit_feature_set": fit.feature_set,
                            "fit_alpha": fit.alpha,
                            "gradient_pred_delta_vs_h012": candidate_delta_prediction(move, cells, fit),
                            "gradient_dot": float(np.mean(move * g)),
                            "public_bad_energy_mean": float(np.mean(cell_energy(move_mat, dirs["bad"]))),
                            "public_good_energy_mean": float(np.mean(cell_energy(move_mat, dirs["good"]))),
                            "private_safe_mean": float(np.mean(cell_private[chosen])),
                            "hs_agree_mean": float(np.mean(cell_hs[chosen])),
                            "mean_abs_delta_prob": float(np.mean(np.abs(delta_prob))),
                            "max_abs_delta_prob": float(np.max(np.abs(delta_prob))),
                            "changed_cells": int(np.sum(np.abs(delta_prob) > 1.0e-6)),
                            "changed_rows": int(np.sum(np.max(np.abs(delta_prob), axis=1) > 1.0e-6)),
                            "q2_share": float(np.mean(cells.iloc[chosen]["target"].eq("Q2"))),
                            "known_file_collision": str(out_path.name) in known_names,
                        }
                    )
    return pd.DataFrame(rows)


def score_variants_with_h024(rt, variants: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    known = rt.h024.read_public_observations()
    refs = rt.h024.build_reference_pack()
    known_rows = [
        {"file": rec["file"], "resolved_path": str(rt.h024.locate(rec["file"]) or rec["file"]), "source": "known_public"}
        for rec in known.to_dict("records")
    ]
    var_rows = variants[["file", "resolved_path"]].copy()
    var_rows["source"] = "h028_public_gradient"
    pool = pd.concat([pd.DataFrame(known_rows), var_rows], ignore_index=True)
    features = rt.h024.build_feature_table(pool, refs)
    known_features = known[["file", "public_lb"]].merge(features, on="file", how="inner")
    blocked = {
        "file",
        "resolved_path",
        "source",
        "pool_file",
        "pool_resolved_path",
        "pool_candidate_id",
        "pool_source",
        "pool_source_candidate_id",
        "pool_source_decision",
        "pool_known_public_lb",
        "known_public_lb",
        "public_lb",
    }
    cols = rt.h024.numeric_feature_cols(known_features, blocked)
    cols_by_set = rt.h024.feature_sets(cols)
    model_scores, loo_preds = rt.h024.evaluate_known_models(known_features[["file", "public_lb"]], features, cols_by_set)
    candidate_scores, pred_samples = rt.h024.score_candidates(known_features[["file", "public_lb"]], features, model_scores, cols_by_set)
    scored = variants.merge(candidate_scores, on="file", how="left", suffixes=("", "_h024"))
    scored["h028_variant_score"] = (
        -1.25 * robust_z(scored["pred_public_median"].fillna(0.580))
        -0.90 * robust_z(scored["gradient_pred_delta_vs_h012"])
        -0.60 * robust_z((scored["pred_public_p90"] - scored["pred_public_p10"]).fillna(0.020))
        +0.70 * robust_z(scored["support_better_than_h012"].fillna(0.0))
        +0.20 * robust_z(scored["private_safe_mean"].fillna(0.0))
        -0.35 * robust_z(scored["public_bad_energy_mean"].fillna(0.0))
        -0.15 * robust_z(scored["max_abs_delta_prob"].fillna(0.0))
    )
    return scored.sort_values("h028_variant_score", ascending=False).reset_index(drop=True), model_scores, pred_samples


def selected_stress(rt, h026, selected: pd.Series) -> tuple[pd.DataFrame, pd.DataFrame]:
    return h026.selected_stress(rt, selected)


def decide(
    selected_fit: GradientFit,
    scored: pd.DataFrame,
    rowperm: pd.DataFrame,
    public_perm: pd.DataFrame,
) -> tuple[str, Path | None]:
    if scored.empty:
        return "no_h028_candidates", None
    top = scored.iloc[0]
    rowperm_p = 1.0
    if not rowperm.empty:
        rowperm_p = float(np.mean(rowperm["perm_top1200_sum"].to_numpy(dtype=np.float64) >= rowperm["real_top1200_sum"].iloc[0]))
    public_perm_p = 1.0
    if not public_perm.empty:
        real_margin = float(top["pred_public_median"] - H012_LB)
        public_perm_p = float(np.mean(public_perm["perm_selected_minus_h012"].to_numpy(dtype=np.float64) <= real_margin))
    gate = (
        selected_fit.public_perm_p <= 0.18
        and selected_fit.loo_pair_acc >= 0.70
        and float(top.get("support_better_than_h012", 0.0)) >= 0.35
        and float(top.get("pred_public_median", 0.58)) <= H012_LB - 0.0002
        and rowperm_p <= 0.25
        and public_perm_p <= 0.20
        and float(top.get("max_abs_delta_prob", 1.0)) <= 0.20
    )
    if not gate:
        return "diagnostic_only_public_gradient_underidentified_or_stress_unsafe", None
    source = Path(str(top["resolved_path"]))
    digest = hashlib.sha1(source.read_bytes()).hexdigest()[:8]
    out = ROOT / f"submission_h028_public_gradient_{digest}_uploadsafe.csv"
    shutil.copyfile(source, out)
    return "primary_public_gradient_hsjepa", out


def write_report(
    known: pd.DataFrame,
    model_scores: pd.DataFrame,
    loo_preds: pd.DataFrame,
    selected_fit: GradientFit,
    variants: pd.DataFrame,
    scored: pd.DataFrame,
    h024_models: pd.DataFrame,
    rowperm: pd.DataFrame,
    public_perm: pd.DataFrame,
    decision: str,
    promoted: Path | None,
) -> None:
    lines = []
    lines.append("# H028 Public/Private Action-Gradient HS-JEPA\n")
    lines.append("## Question\n")
    lines.append(
        "H012 made a large public jump, but H015-H027 mostly failed when they tried to complete posterior targets after H012. "
        "H028 asks a different JEPA question: from the context of known public interventions, can we predict the hidden public/private action-gradient for each cell?\n"
    )
    lines.append("## Known public sensors\n")
    lines.append(f"- sensors used: `{len(known)}`\n")
    lines.append(md_table(known[["file", "public_lb", "delta_vs_h012", "mean_abs_logit_move", "changed_cells"]], 20) + "\n")
    lines.append("## Gradient fit\n")
    lines.append(
        f"- selected fit: `{selected_fit.feature_set}` alpha `{selected_fit.alpha}` with `{len(selected_fit.cols)}` features\n"
        f"- LOO MAE `{selected_fit.loo_mae:.9f}`, RMSE `{selected_fit.loo_rmse:.9f}`, "
        f"Spearman `{selected_fit.loo_spearman:.6f}`, pairwise `{selected_fit.loo_pair_acc:.6f}`\n"
        f"- permutation p(best selected LOO MAE under shuffled public deltas): `{selected_fit.public_perm_p:.9f}`\n"
    )
    lines.append(md_table(model_scores[["feature_set", "alpha", "n_features", "loo_mae", "loo_rmse", "loo_spearman", "loo_pair_acc", "public_perm_p"]], 12) + "\n")
    lines.append("## Generated variants\n")
    lines.append(f"- generated variants: `{len(variants)}`\n")
    if not scored.empty:
        lines.append(
            md_table(
                scored[
                    [
                        "file",
                        "mode",
                        "target_subset",
                        "top_k",
                        "alpha",
                        "gradient_pred_delta_vs_h012",
                        "pred_public_median",
                        "pred_public_p10",
                        "pred_public_p90",
                        "support_better_than_h012",
                        "h028_variant_score",
                    ]
                ],
                15,
            )
            + "\n"
        )
    lines.append("## Stress\n")
    if not h024_models.empty:
        top_model = h024_models.iloc[0]
        lines.append(
            f"- H024 decoder in H028 pool: `{top_model['feature_set']}` alpha `{top_model['alpha']}`, "
            f"MAE `{top_model['loo_mae']:.9f}`, Spearman `{top_model['loo_spearman']:.6f}`, pairwise `{top_model['loo_pair_acc']:.6f}`\n"
        )
    if not rowperm.empty:
        rowperm_p = float(np.mean(rowperm["perm_top1200_sum"].to_numpy(dtype=np.float64) >= rowperm["real_top1200_sum"].iloc[0]))
        lines.append(f"- H025 row-permutation p(higher top1200 gain): `{rowperm_p:.9f}`\n")
        lines.append(f"- real H025 top1200 gain: `{float(rowperm['real_top1200_sum'].iloc[0]):.9f}`\n")
    if not public_perm.empty and not scored.empty:
        real_margin = float(scored.iloc[0]["pred_public_median"] - H012_LB)
        public_perm_p = float(np.mean(public_perm["perm_selected_minus_h012"].to_numpy(dtype=np.float64) <= real_margin))
        lines.append(f"- H024 public-score permutation p(lower margin): `{public_perm_p:.9f}`\n")
        lines.append(f"- selected predicted public margin vs H012: `{real_margin:.9f}`\n")
    lines.append("## Decision\n")
    lines.append(f"- decision: `{decision}`\n")
    lines.append(f"- promoted path: `{promoted if promoted is not None else 'none'}`\n")
    lines.append(
        "\nInterpretation: if H028 passes, HS-JEPA has learned a public/private intervention gradient rather than a posterior-completion gate. "
        "If it fails, the current public observations are insufficient to identify a new post-H012 action field; H012 remains an isolated public-equation event.\n"
    )
    (OUT / "h028_report.md").write_text("".join(lines))


def main() -> None:
    h026, rt = load_runtime()
    cells, feature_sets = build_cell_state(rt)
    cells.to_csv(OUT / "h028_cell_state.csv", index=False)
    pd.DataFrame(
        [{"feature_set": k, "n_features": len(v), "features": ",".join(v)} for k, v in feature_sets.items()]
    ).to_csv(OUT / "h028_feature_sets.csv", index=False)

    known = known_public_moves(rt, cells)
    known.drop(columns=["move_logit"]).to_csv(OUT / "h028_known_public_interventions.csv", index=False)
    model_scores, loo_preds, selected_fit = evaluate_gradient_models(known, cells, feature_sets)
    model_scores.to_csv(OUT / "h028_gradient_model_scores.csv", index=False)
    loo_preds.to_csv(OUT / "h028_gradient_loo_predictions.csv", index=False)

    g = gradient_vector(cells, selected_fit)
    grad_cells = cells[["row", "target", "target_i"]].copy()
    grad_cells["public_gradient"] = g
    grad_cells["gradient_abs_rank"] = pd.Series(np.abs(g)).rank(method="average", ascending=False).to_numpy(dtype=np.float64)
    grad_cells.to_csv(OUT / "h028_cell_public_gradient.csv", index=False)

    variants = generate_variants(rt, h026, cells, selected_fit, known)
    variants.to_csv(OUT / "h028_generated_variants_raw.csv", index=False)
    if variants.empty:
        scored = variants
        h024_models = pd.DataFrame()
        pred_samples = pd.DataFrame()
        rowperm = pd.DataFrame()
        public_perm = pd.DataFrame()
        decision, promoted = "no_h028_generated_variants", None
    else:
        scored, h024_models, pred_samples = score_variants_with_h024(rt, variants)
        scored.to_csv(OUT / "h028_variant_scores.csv", index=False)
        h024_models.to_csv(OUT / "h028_h024_model_scores.csv", index=False)
        pred_samples.to_csv(OUT / "h028_h024_prediction_samples.csv", index=False)
        selected = scored.iloc[0]
        rowperm, public_perm = selected_stress(rt, h026, selected)
        rowperm.to_csv(OUT / "h028_selected_h025_rowperm_stress.csv", index=False)
        public_perm.to_csv(OUT / "h028_selected_h024_public_perm_stress.csv", index=False)
        decision, promoted = decide(selected_fit, scored, rowperm, public_perm)

    pd.DataFrame([{"decision": decision, "promoted_path": str(promoted) if promoted is not None else ""}]).to_csv(
        OUT / "h028_decision.csv", index=False
    )
    write_report(
        known.drop(columns=["move_logit"]),
        model_scores,
        loo_preds,
        selected_fit,
        variants,
        scored,
        h024_models,
        rowperm,
        public_perm,
        decision,
        promoted,
    )

    print(f"H028 decision: {decision}")
    print(f"H028 selected fit: {selected_fit.feature_set} alpha={selected_fit.alpha} LOO={selected_fit.loo_mae:.9f} p={selected_fit.public_perm_p:.6f}")
    if not scored.empty:
        top = scored.iloc[0]
        print(
            "H028 top:",
            top["file"],
            "pred_public",
            float(top.get("pred_public_median", np.nan)),
            "support",
            float(top.get("support_better_than_h012", np.nan)),
        )
    if promoted is not None:
        print(f"H028 promoted: {promoted}")


if __name__ == "__main__":
    main()
