#!/usr/bin/env python3
"""Subject-heldout route responsibility diagnostic for HS-JEPA.

Subject-balanced route conservation was positive, but it still selected target
routes after seeing all subjects.  This diagnostic is stricter:

    for each held-out subject:
      choose target-route policies using all other subjects only
      apply those policies to the held-out subject
      measure realized row-target action gain

The support scores themselves are generated by the public-free HS-JEPA
listener-conditioned action-support pipeline; route selection and evaluation do
not use public LB, prior submission probabilities, or proprietary embeddings.

This is a LeJEPA-style diagnostic adapter.  It is not HS-JEPA core itself.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hsjepa_core.run_action_support_world_model_core import TARGETS, validate_submission  # noqa: E402
from hsjepa_core.run_lifelog_core_state_evidence import format_float, markdown_table  # noqa: E402
from sleep_competition_adapter.subject_balanced_route_conservation_decoder import (  # noqa: E402
    ROUTE_CONSERVATION_GAIN_REFERENCE,
    choose_subject_balanced_routes,
    policy_subject_audit,
    subject_audit_summary,
)
from sleep_competition_adapter.target_route_conservation_decoder import (  # noqa: E402
    LISTENER_GLOBAL_GAIN_REFERENCE,
    SAMPLE_SUBMISSION,
    apply_conserved_routes_to_oof,
    apply_conserved_routes_to_test,
    build_listener_cells,
    route_policy_grid,
    short_hash,
    target_summary,
)


OUT_DIR = ROOT / "sleep_competition_adapter" / "outputs" / "subject_heldout_route_responsibility_diagnostic"
PAPER_DOC = ROOT / "paper_hsjepa_core" / "SUBJECT_HELDOUT_ROUTE_RESPONSIBILITY_DIAGNOSTIC_KO.md"


def select_subject_balanced_routes(cells: pd.DataFrame, score_col: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    grid = route_policy_grid(cells, score_col)
    subject_grid, _subject_policy_audit = policy_subject_audit(cells, grid, score_col)
    chosen = choose_subject_balanced_routes(subject_grid)
    return chosen, subject_grid


def run_subject_heldout(train_cells: pd.DataFrame, score_col: str) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    subjects = sorted(train_cells["subject_id"].astype(str).unique())
    fold_rows: list[dict[str, Any]] = []
    route_rows: list[dict[str, Any]] = []
    heldout_audits: list[pd.DataFrame] = []
    for subject in subjects:
        selector_cells = train_cells[~train_cells["subject_id"].astype(str).eq(subject)].copy()
        heldout_cells = train_cells[train_cells["subject_id"].astype(str).eq(subject)].copy()
        chosen, _subject_grid = select_subject_balanced_routes(selector_cells, score_col)
        heldout_audit = apply_conserved_routes_to_oof(heldout_cells, chosen, score_col)
        heldout_audit["heldout_subject"] = subject
        heldout_audits.append(heldout_audit)
        selected = heldout_audit[heldout_audit["released"]].copy()
        gain = selected["effective_gain"].to_numpy(dtype=np.float64) if len(selected) else np.array([], dtype=np.float64)
        fold_rows.append(
            {
                "heldout_subject": subject,
                "selected_cells": int(len(selected)),
                "gain_sum": float(gain.sum()) if len(gain) else 0.0,
                "mean_gain": float(gain.mean()) if len(gain) else 0.0,
                "positive_gain_rate": float((gain > 0).mean()) if len(gain) else np.nan,
                "accepted_targets": ",".join(chosen.loc[chosen["accepted"].eq(True), "target"].astype(str).tolist()),
                "held_targets": ",".join(chosen.loc[chosen["accepted"].eq(False), "target"].astype(str).tolist()),
            }
        )
        for _, row in chosen.iterrows():
            target = str(row["target"])
            selected_target = selected[selected["target"].eq(target)]
            route_rows.append(
                {
                    "heldout_subject": subject,
                    "target": target,
                    "accepted": bool(row["accepted"]),
                    "policy": str(row["policy"]),
                    "decoder_action": str(row["decoder_action"]),
                    "fraction": float(row["fraction"]),
                    "heldout_selected_cells": int(len(selected_target)),
                    "heldout_gain_sum": float(selected_target["effective_gain"].sum()) if len(selected_target) else 0.0,
                    "heldout_positive_gain_rate": float((selected_target["effective_gain"] > 0).mean()) if len(selected_target) else np.nan,
                    "accept_reason": str(row["accept_reason"]),
                }
            )
    return pd.DataFrame(fold_rows), pd.DataFrame(route_rows), pd.concat(heldout_audits, ignore_index=True)


def summarize_heldout_targets(heldout_audit: pd.DataFrame) -> pd.DataFrame:
    selected = heldout_audit[heldout_audit["released"]].copy()
    if selected.empty:
        return pd.DataFrame(columns=["target", "selected_cells", "gain_sum", "positive_gain_rate", "positive_subjects", "negative_subjects"])
    by_subject_target = (
        selected.groupby(["heldout_subject", "target"], observed=True)["effective_gain"]
        .sum()
        .reset_index()
    )
    target_subjects = (
        by_subject_target.groupby("target", observed=True)
        .agg(
            positive_subjects=("effective_gain", lambda x: int((x > 0).sum())),
            negative_subjects=("effective_gain", lambda x: int((x < 0).sum())),
        )
        .reset_index()
    )
    target_cells = (
        selected.groupby("target", observed=True)
        .agg(
            selected_cells=("effective_gain", "size"),
            gain_sum=("effective_gain", "sum"),
            mean_gain=("effective_gain", "mean"),
            positive_gain_rate=("effective_gain", lambda x: float((x > 0).mean())),
        )
        .reset_index()
    )
    return target_cells.merge(target_subjects, on="target", how="left").sort_values("target")


def stable_routes_from_heldout(full_chosen: pd.DataFrame, route_rows: pd.DataFrame, target_summary_frame: pd.DataFrame) -> pd.DataFrame:
    target_stats = target_summary_frame.set_index("target").to_dict(orient="index")
    route_accept_rate = route_rows.groupby("target", observed=True)["accepted"].mean().to_dict()
    route_rows = route_rows.copy()
    stable_rows = []
    for _, route in full_chosen.iterrows():
        row = route.to_dict()
        target = str(row["target"])
        stats = target_stats.get(target, {})
        accept_rate = float(route_accept_rate.get(target, 0.0))
        gain_sum = float(stats.get("gain_sum", 0.0))
        positive_subjects = int(stats.get("positive_subjects", 0))
        negative_subjects = int(stats.get("negative_subjects", 0))
        positive_rate = float(stats.get("positive_gain_rate", 0.0)) if pd.notna(stats.get("positive_gain_rate", np.nan)) else 0.0
        stable = (
            bool(row.get("accepted", False))
            and accept_rate >= 0.60
            and gain_sum > 0.0
            and positive_subjects >= max(2, negative_subjects + 1)
            and positive_rate >= 0.60
        )
        row["accepted"] = stable
        row["heldout_accept_rate"] = accept_rate
        row["heldout_gain_sum"] = gain_sum
        row["heldout_positive_subjects"] = positive_subjects
        row["heldout_negative_subjects"] = negative_subjects
        row["heldout_positive_gain_rate"] = positive_rate
        row["accept_reason"] = (
            "heldout_stable_subject_route_responsibility"
            if stable
            else "failed_subject_heldout_route_responsibility"
        )
        if not stable:
            row["policy"] = "hold"
            row["decoder_action"] = "none"
            row["fraction"] = 0.0
            row["selected_cells"] = 0
        stable_rows.append(row)
    return pd.DataFrame(stable_rows).sort_values("target")


def route_decision_frequency(route_rows: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for target, part in route_rows.groupby("target", observed=True):
        decision = Counter(
            f"{policy}|{decoder}|{fraction:.2f}"
            for policy, decoder, fraction in zip(part["policy"], part["decoder_action"], part["fraction"])
        )
        top_decision, top_count = decision.most_common(1)[0]
        rows.append(
            {
                "target": target,
                "heldout_accept_rate": float(part["accepted"].mean()),
                "top_decision": top_decision,
                "top_decision_count": int(top_count),
                "heldout_gain_sum": float(part["heldout_gain_sum"].sum()),
                "heldout_positive_subjects": int((part["heldout_gain_sum"] > 0).sum()),
                "heldout_negative_subjects": int((part["heldout_gain_sum"] < 0).sum()),
            }
        )
    return pd.DataFrame(rows).sort_values("target")


def build_markdown(
    summary: dict[str, Any],
    fold_summary: pd.DataFrame,
    target_summary_frame: pd.DataFrame,
    route_frequency: pd.DataFrame,
    stable_routes: pd.DataFrame,
) -> str:
    return f"""# HS-JEPA Diagnostic Adapter: Subject-Heldout Route Responsibility

## 한 줄 요약

subject-balanced route conservation이 모든 subject를 보고 고른 균형인지,
아니면 held-out subject에도 전이되는 route responsibility인지 검사했다.

```text
for each held-out subject:
  train subjects only -> choose target-route policy
  held-out subject only -> apply selected policy
  measure realized action gain
```

## 빠른 판정: 이것은 HS-JEPA인가?

**HS-JEPA core 자체는 아니다.**
정확한 위치는 **LeJEPA-style diagnostic adapter**다.

```text
HS-JEPA core
  = visible human-life context -> hidden world-state representation

이 문서의 역할
  = 그 representation이 만든 target-route action law가 subject shortcut인지 반증한다.
```

## 사용하지 않은 정보

- public LB ledger: `{summary["uses_public_score_ledger"]}`
- prior submission probability: `{summary["uses_prior_submission_probabilities"]}`
- proprietary embedding API: `{summary["uses_proprietary_embedding_api"]}`

## Verdict

- verdict: `{summary["verdict"]}`
- heldout selected cells: `{summary["heldout_selected_cells"]}`
- heldout gain sum: `{format_float(summary["heldout_gain_sum"], 6)}`
- heldout positive gain rate: `{format_float(summary["heldout_positive_gain_rate"], 6)}`
- positive heldout subjects: `{summary["positive_heldout_subjects"]}`
- negative heldout subjects: `{summary["negative_heldout_subjects"]}`
- listener global gain reference: `{format_float(summary["listener_global_gain_reference"], 6)}`
- subject-balanced gain reference: `{format_float(summary["subject_balanced_gain_reference"], 6)}`
- stable targets for candidate: `{summary["stable_targets"]}`
- released test cells: `{summary["released_test_cells"]}`

## Heldout Subject Summary

{markdown_table(fold_summary, ["heldout_subject", "selected_cells", "gain_sum", "mean_gain", "positive_gain_rate", "accepted_targets", "held_targets"], max_rows=20)}

## Heldout Target Summary

{markdown_table(target_summary_frame, ["target", "selected_cells", "gain_sum", "mean_gain", "positive_gain_rate", "positive_subjects", "negative_subjects"], max_rows=20)}

## Route Decision Frequency

{markdown_table(route_frequency, ["target", "heldout_accept_rate", "top_decision", "top_decision_count", "heldout_gain_sum", "heldout_positive_subjects", "heldout_negative_subjects"], max_rows=20)}

## Stable Routes Used For Candidate

{markdown_table(stable_routes, ["target", "accepted", "policy", "decoder_action", "fraction", "heldout_accept_rate", "heldout_gain_sum", "heldout_positive_subjects", "heldout_negative_subjects", "heldout_positive_gain_rate", "accept_reason"], max_rows=20)}

## Anchor-Free Candidate

- candidate: `{summary["candidate_file"]}`
- validation: `{summary["validation"]}`

## 해석

좋은 결과:

```text
held-out subject를 route selection에서 완전히 제거해도 gain이 양수이면,
HS-JEPA route responsibility는 단순 subject-tail shortcut만은 아니다.
```

나쁜 결과:

```text
subject-balanced에서는 양수였지만 subject-heldout에서 무너지면,
현재 route law는 OOF balancing artifact이고 release-grade 일반 법칙은 아니다.
```

현재 결론:

```text
이번 결과는 negative/fragile이다.
subject-balanced route law는 모든 subject를 본 OOF audit에서는 강했지만,
subject를 완전히 가린 선택-평가에서는 전체 gain이 음수로 무너졌다.
따라서 현재 target-route decoder를 subject-general HS-JEPA law로 주장하면 안 된다.

다만 Q3/S4 route만 조건부로 살아남았으므로,
다음 core 연구는 전체 sparse action release가 아니라
target별 listener responsibility와 subject-heldout action toxicity를 분리해야 한다.
```
"""


def run() -> dict[str, Any]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    score_col = "support_score_target_interaction_world_residual_energy"
    train_cells, test_cells, train_priors, _view_metrics = build_listener_cells()

    full_chosen, _full_subject_grid = select_subject_balanced_routes(train_cells, score_col)
    fold_summary, route_rows, heldout_audit = run_subject_heldout(train_cells, score_col)
    heldout_selected = heldout_audit[heldout_audit["released"]].copy()
    target_summary_frame = summarize_heldout_targets(heldout_audit)
    route_frequency = route_decision_frequency(route_rows)
    stable_routes = stable_routes_from_heldout(full_chosen, route_rows, target_summary_frame)
    stable_oof_audit = apply_conserved_routes_to_oof(train_cells, stable_routes, score_col)
    stable_target_summary = target_summary(stable_oof_audit)
    stable_subject_summary = subject_audit_summary(stable_oof_audit)

    sample = pd.read_csv(SAMPLE_SUBMISSION)
    candidate, test_audit = apply_conserved_routes_to_test(sample, test_cells, stable_routes, score_col, train_priors)
    validation = validate_submission(candidate, sample)
    if not validation["valid"]:
        raise ValueError(f"candidate is not upload-safe: {validation['problems']}")
    candidate_name = f"submission_hsjepa_subject_heldout_route_responsibility_anchor_free_{short_hash(candidate)}_uploadsafe.csv"
    heldout_gain = float(heldout_selected["effective_gain"].sum()) if len(heldout_selected) else 0.0
    heldout_positive_rate = float((heldout_selected["effective_gain"] > 0).mean()) if len(heldout_selected) else np.nan
    positive_subjects = int((fold_summary["gain_sum"] > 0).sum())
    negative_subjects = int((fold_summary["gain_sum"] < 0).sum())
    stable_targets = stable_routes.loc[stable_routes["accepted"].eq(True), "target"].astype(str).tolist()
    summary = {
        "package": "subject_heldout_route_responsibility_diagnostic",
        "status": "subject_heldout_route_responsibility_ready",
        "uses_public_score_ledger": False,
        "uses_prior_submission_probabilities": False,
        "uses_proprietary_embedding_api": False,
        "verdict": "subject_heldout_route_responsibility_positive" if heldout_gain > 0 and positive_subjects > negative_subjects else "subject_heldout_route_responsibility_negative_or_fragile",
        "heldout_selected_cells": int(len(heldout_selected)),
        "heldout_gain_sum": heldout_gain,
        "heldout_positive_gain_rate": heldout_positive_rate,
        "positive_heldout_subjects": positive_subjects,
        "negative_heldout_subjects": negative_subjects,
        "listener_global_gain_reference": LISTENER_GLOBAL_GAIN_REFERENCE,
        "subject_balanced_gain_reference": 10.122798836819854,
        "route_conservation_gain_reference": ROUTE_CONSERVATION_GAIN_REFERENCE,
        "stable_targets": stable_targets,
        "stable_oof_gain_sum": float(stable_oof_audit["effective_gain"].sum()),
        "stable_oof_selected_cells": int(stable_oof_audit["released"].sum()),
        "released_test_cells": int(test_audit["released"].sum()),
        "candidate_file": candidate_name,
        "validation": validation,
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    fold_summary.to_csv(OUT_DIR / "heldout_subject_summary.csv", index=False)
    route_rows.to_csv(OUT_DIR / "heldout_route_decisions.csv", index=False)
    heldout_audit.to_csv(OUT_DIR / "heldout_oof_audit.csv", index=False)
    target_summary_frame.to_csv(OUT_DIR / "heldout_target_summary.csv", index=False)
    route_frequency.to_csv(OUT_DIR / "heldout_route_decision_frequency.csv", index=False)
    stable_routes.to_csv(OUT_DIR / "stable_subject_heldout_routes.csv", index=False)
    stable_oof_audit.to_csv(OUT_DIR / "stable_subject_heldout_oof_audit.csv", index=False)
    stable_target_summary.to_csv(OUT_DIR / "stable_subject_heldout_target_summary.csv", index=False)
    stable_subject_summary.to_csv(OUT_DIR / "stable_subject_heldout_subject_summary.csv", index=False)
    test_audit.to_csv(OUT_DIR / "stable_subject_heldout_test_audit.csv", index=False)
    candidate.to_csv(OUT_DIR / candidate_name, index=False)
    candidate.to_csv(ROOT / candidate_name, index=False)
    (OUT_DIR / "subject_heldout_route_responsibility_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    md = build_markdown(summary, fold_summary, target_summary_frame, route_frequency, stable_routes)
    (OUT_DIR / "SUBJECT_HELDOUT_ROUTE_RESPONSIBILITY_DIAGNOSTIC_KO.md").write_text(md.rstrip() + "\n", encoding="utf-8")
    PAPER_DOC.write_text(md.rstrip() + "\n", encoding="utf-8")
    return summary


if __name__ == "__main__":
    print(json.dumps(run(), ensure_ascii=False, indent=2))
